apiVersion: v1
kind: ConfigMap
metadata:
  name: acme-app-config
  namespace: acme-developer-hub
data:
  app-config.yaml: |
    app:
      branding:
        fullLogo: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNTAwIiBoZWlnaHQ9IjI1MDAiIHZpZXdCb3g9IjAgMCAxOTIuNzU2IDE5Mi43NTYiPjxnIGZpbGwtcnVsZT0iZXZlbm9kZCIgY2xpcC1ydWxlPSJldmVub2RkIj48cGF0aCBmaWxsPSIjZmZmIiBkPSJNMCAwaDE5Mi43NTZ2MTkyLjc1NkgwVjB6Ii8+PHBhdGggZD0iTTIzLjQ1NCA2OC43ODVsLTIwLjYyIDU1LjQ4OGgxNS43NjhsMi43MjktNy44ODNIMzMuNDZ2Ny44ODNoMTUuNDY0VjY4Ljc4NWgtMjUuNDd6bTkuNzAzIDMxLjUzNWgtNi4zNjhsNi4zNjgtMTMuMzQydjEzLjM0MnpNOTQuNzEgNjguMTc4SDcwLjE0OWMtOC4xODggMC0xMC45MTYgMTAuNjEzLTEwLjkxNiAxMC42MTNsLTUuNzYxIDMzLjA1MXMtMi4xMjMgMTIuNDMyIDguNDkgMTIuNDMyaDIzLjA0NWwyLjQyNi0xNi4zNzNINzUuMDAxcy01LjQ1OCAxLjIxMy00LjU0OC00Ljg1MmMuMzAzLS45MSAyLjQyNi0xMy4wMzkgMi40MjYtMTMuMDM5cy42MDYtNC4yNDUgMy4zMzUtNC4yNDVoMTUuNDY0bDMuMDMyLTE3LjU4N3pNMTAxLjk4OCA2OC40ODJsLTExLjUyMyA1NS43OTFoMTUuMTYybDUuMTU0LTIzLjY1IDEuMjEzIDIzLjY1aDguMTg4bDkuMDk1LTIzLjY1LTQuNTQ4IDIzLjY1aDEzLjY0NGwxMS4yMjEtNTYuMDk1aC0xOS40MDZsLTkuNDAxIDIzLjM0OFY2OC40ODJoLTE4Ljc5OXpNMTQ1Ljk1NSAxMjQuMjczbDEwLjYxMS01Ni4wOTVoMzEuMjMzbC0yLjQyNiAxNi4wNzJIMTY5bC0uOTEgNS40NTdoMTUuNzY3bC0yLjQyNSAxMi4xMjktMTYuMDcxLS4zMDMtLjkxIDUuNDU3aDE2LjA3bC0zLjMzNSAxNy4yODNoLTMxLjIzMXpNMTg1LjA3IDEyMy4zNjVjLTIuMTIzIDAtMy4zMzYtMS41MTgtMy4zMzYtMy42MzkgMC0yLjEyMyAxLjIxMy0zLjYzOSAzLjMzNi0zLjYzOXMzLjYzOSAxLjUxNiAzLjYzOSAzLjYzOWMwIDIuMTIyLTEuNTE2IDMuNjM5LTMuNjM5IDMuNjM5em0wIDEuMjEzYzIuNzI5IDAgNC44NTItMi40MjYgNC44NTItNC44NTIgMC0yLjcyOS0yLjEyMy00Ljg1Mi00Ljg1Mi00Ljg1MnMtNC44NTIgMi4xMjMtNC44NTIgNC44NTJjLjAwMSAyLjQyNiAyLjEyNCA0Ljg1MiA0Ljg1MiA0Ljg1MnptMS4yMTMtNC41NDljLjkxIDAgMS41MTYtLjMwMyAxLjUxNi0xLjUxNnMtLjkxLTEuNTE2LTIuMTIzLTEuNTE2aC0yLjQyNnY1LjE1NGguOTF2LTIuMTIzaC45MWwxLjIxMyAyLjEyM2gxLjIxM2wtMS4yMTMtMi4xMjJ6bS0yLjEyMy0uNjA3di0xLjUxNmgxLjIxM2MuNjA3IDAgMS4yMTMgMCAxLjIxMy42MDcgMCAuNjA1LS4zMDMuOTA4LS45MS45MDhoLTEuNTE2di4wMDF6IiBmaWxsPSIjY2Q1MjQxIi8+PC9nPjwvc3ZnPg==
        iconLogo: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNTAwIiBoZWlnaHQ9IjI1MDAiIHZpZXdCb3g9IjAgMCAxOTIuNzU2IDE5Mi43NTYiPjxnIGZpbGwtcnVsZT0iZXZlbm9kZCIgY2xpcC1ydWxlPSJldmVub2RkIj48cGF0aCBmaWxsPSIjZmZmIiBkPSJNMCAwaDE5Mi43NTZ2MTkyLjc1NkgwVjB6Ii8+PHBhdGggZD0iTTIzLjQ1NCA2OC43ODVsLTIwLjYyIDU1LjQ4OGgxNS43NjhsMi43MjktNy44ODNIMzMuNDZ2Ny44ODNoMTUuNDY0VjY4Ljc4NWgtMjUuNDd6bTkuNzAzIDMxLjUzNWgtNi4zNjhsNi4zNjgtMTMuMzQydjEzLjM0MnpNOTQuNzEgNjguMTc4SDcwLjE0OWMtOC4xODggMC0xMC45MTYgMTAuNjEzLTEwLjkxNiAxMC42MTNsLTUuNzYxIDMzLjA1MXMtMi4xMjMgMTIuNDMyIDguNDkgMTIuNDMyaDIzLjA0NWwyLjQyNi0xNi4zNzNINzUuMDAxcy01LjQ1OCAxLjIxMy00LjU0OC00Ljg1MmMuMzAzLS45MSAyLjQyNi0xMy4wMzkgMi40MjYtMTMuMDM5cy42MDYtNC4yNDUgMy4zMzUtNC4yNDVoMTUuNDY0bDMuMDMyLTE3LjU4N3pNMTAxLjk4OCA2OC40ODJsLTExLjUyMyA1NS43OTFoMTUuMTYybDUuMTU0LTIzLjY1IDEuMjEzIDIzLjY1aDguMTg4bDkuMDk1LTIzLjY1LTQuNTQ4IDIzLjY1aDEzLjY0NGwxMS4yMjEtNTYuMDk1aC0xOS40MDZsLTkuNDAxIDIzLjM0OFY2OC40ODJoLTE4Ljc5OXpNMTQ1Ljk1NSAxMjQuMjczbDEwLjYxMS01Ni4wOTVoMzEuMjMzbC0yLjQyNiAxNi4wNzJIMTY5bC0uOTEgNS40NTdoMTUuNzY3bC0yLjQyNSAxMi4xMjktMTYuMDcxLS4zMDMtLjkxIDUuNDU3aDE2LjA3bC0zLjMzNSAxNy4yODNoLTMxLjIzMXpNMTg1LjA3IDEyMy4zNjVjLTIuMTIzIDAtMy4zMzYtMS41MTgtMy4zMzYtMy42MzkgMC0yLjEyMyAxLjIxMy0zLjYzOSAzLjMzNi0zLjYzOXMzLjYzOSAxLjUxNiAzLjYzOSAzLjYzOWMwIDIuMTIyLTEuNTE2IDMuNjM5LTMuNjM5IDMuNjM5em0wIDEuMjEzYzIuNzI5IDAgNC44NTItMi40MjYgNC44NTItNC44NTIgMC0yLjcyOS0yLjEyMy00Ljg1Mi00Ljg1Mi00Ljg1MnMtNC44NTIgMi4xMjMtNC44NTIgNC44NTJjLjAwMSAyLjQyNiAyLjEyNCA0Ljg1MiA0Ljg1MiA0Ljg1MnptMS4yMTMtNC41NDljLjkxIDAgMS41MTYtLjMwMyAxLjUxNi0xLjUxNnMtLjkxLTEuNTE2LTIuMTIzLTEuNTE2aC0yLjQyNnY1LjE1NGguOTF2LTIuMTIzaC45MWwxLjIxMyAyLjEyM2gxLjIxM2wtMS4yMTMtMi4xMjJ6bS0yLjEyMy0uNjA3di0xLjUxNmgxLjIxM2MuNjA3IDAgMS4yMTMgMCAxLjIxMy42MDcgMCAuNjA1LS4zMDMuOTA4LS45MS45MDhoLTEuNTE2di4wMDF6IiBmaWxsPSIjY2Q1MjQxIi8+PC9nPjwvc3ZnPg==
      title: ACME Developer Hub (Production)
      baseUrl: https://acme.apps.sno.neat-monster.com
      custom:
        helpPageUrl: https://www.acme.com/help
        aboutPageUrl: https://www.acme.com/about
      quickstart:
      - title: 'Welcome to ACME Developer Hub'
        description: 'Learn the basics of navigating the Developer Hub interface'
        icon: 'home'
        cta:
          text: 'Get Started'
          link: '/catalog'
      - title: 'Create Your First Component'
        description: 'Follow our guide to register your first software component'
        icon: 'code'
        cta:
          text: 'Create Component'
          link: '/catalog-import'
      - title: 'Explore Templates'
        description: 'Discover available software templates to bootstrap new projects'
        icon: 'template'
        cta:
          text: 'Browse Templates'
          link: '/create'  
    auth:
      environment: production
      providers:
        oidc:
          development:
            clientId: openshift
            clientSecret: ${KEYCLOAK_OPENSHIFT_CLIENT_SECRET}
            metadataUrl: https://keycloak-rhsso.apps.sno.neat-monster.com/realms/openshift-sso/.well-known/openid-configuration
            prompt: auto
            sessionDuration: { hours: 24 }
            signIn:
              dangerouslyAllowSignInWithoutUserInCatalog: true
        microsoft:
          production:
            clientId: ${AZURE_CLIENT_ID}
            clientSecret: ${AZURE_CLIENT_SECRET}
            tenantId: ${AZURE_TENANT_ID}
          development:
            clientId: ${AZURE_CLIENT_ID}
            clientSecret: ${AZURE_CLIENT_SECRET}
            tenantId: ${AZURE_TENANT_ID}
        guest:
            dangerouslyAllowOutsideDevelopment: true
            userEntityRef: user:default/guest
    signInPage: microsoft
    permission:
      enabled: true
      rbac:
        admin:
          users:
            - name: user:default/sumiranchugh
            - name: user:default/sumiranchugh_outlook.com
            - name: group:default/team_a
    enabled:
      microsoftGraphOrg: true
      permission: true
      kubernetes: true
      techdocs: true   
    catalog:
      useUrlReadersSearch: true
      rules:
        - allow: [Component, API, Resource, System, Domain, Group, User, Location, Template]
      locations:
      - target: https://dev.azure.com/sumiranchugh/rhdh-ado-project/_git/red-hat-developer-hub-software-templates?path=/templates.yaml
        type: url
        rules:
        - allow: [Component, API, Resource, System, Domain, Group, User, Location, Template]
      providers:
        keycloakOrg:
          default:
            baseUrl: https://keycloak-rhsso.apps.sno.neat-monster.com
            realm: openshift-sso
            loginRealm: openshift-sso
            clientId: rhdh-sync
            clientSecret: ${KEYCLOAK_SYNC_CLIENT_SECRET}
            schedule:
              frequency: PT5M   # sync every 5 minutes
              timeout: PT2M
            userTransformer:
              name: "username"       
        microsoftGraphOrg:
          providerId:
            clientId: ${AZURE_CLIENT_ID}
            clientSecret: ${AZURE_CLIENT_SECRET}
            tenantId: ${AZURE_TENANT_ID}
            queryMode: advanced
            # Ingest GROUP entities: the root group and all nested groups
            group:
            # Root group + all nested groups (transitive)
              path: /groups/d430aa17-2f9d-4f4e-93d5-1350fe816c4c/transitiveMembers/microsoft.graph.group
              includeSubGroups: true   # harmless here; path already returns nested groups

            # Ingest USER entities: all users who are transitive members of that root group
            user:
              path: /groups/d430aa17-2f9d-4f4e-93d5-1350fe816c4c/transitiveMembers/microsoft.graph.user

            #userGroupMember:
              #search: '"displayName:team a" OR "displayName:teamb" OR "id:d430aa17-2f9d-4f4e-93d5-1350fe816c4c"'
              # filter: 'startswith(displayName,''team a'') or startswith(displayName,''teamb'')'
            schedule:
              frequency: PT1M
              timeout: PT50M
        azureDevOps:
          yourProviderId: # identifies your dataset / provider independent of config changes
            organization: sumiranchugh
            project: '*'
            repository: '*' # this will match all repos 
            path: /catalog-info.yaml
            schedule: # optional; same options as in TaskScheduleDefinition
              # supports cron, ISO duration, "human duration" as used in code
              frequency: { minutes: 3 }
              # supports ISO duration, "human duration" as used in code
              timeout: { minutes: 3 }

        # kubernetes:
        #   openshift:
        #     cluster: openshift
        #     processor:
        #       namespaceOverride: default
        #       defaultOwner: guests
        #     schedule:
        #       frequency:
        #         seconds: 30
        #       timeout:
        #         seconds: 5
    kubernetes:
      serviceLocatorMethod:
        type: 'multiTenant'
      clusterLocatorMethods:
        - type: 'config'
          clusters:
            - url:  https://kubernetes.default.svc
              name: openshift
              authProvider: 'serviceAccount'
              skipTLSVerify: false 
              skipMetricsLookup: true
              caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      customResources:
        - group: 'tekton.dev'
          apiVersion: 'v1beta1'
          plural: 'pipelineruns'
        - group: 'tekton.dev'
          apiVersion: 'v1beta1'
          plural: 'taskruns'
        - group: 'route.openshift.io'
          apiVersion: 'v1'
          plural: 'routes'        
    argocd:
      appLocatorMethods:
        - type: 'config'
          instances:
            - name: argoInstance1
              token: "${ARGOCD_AUTH_TOKEN}"
              url: http://openshift-gitops-server.openshift-gitops.svc.cluster.local      
    integrations:
      github:
      - host: github.com
        token: ${GITHUB_TOKEN}
      azure:
        - host: dev.azure.com
          credentials:
            # - personalAccessToken: \${AZURE_DEVOPS_PERSONAL_ACCESS_TOKEN}
            #   organizations:
            #     - \$AZURE_DEVOPS_ORG
            - clientId: ${AZURE_CLIENT_ID}
              clientSecret: ${AZURE_CLIENT_SECRET}
              tenantId: ${AZURE_TENANT_ID}
              # organizations:
              #   - \$AZURE_DEVOPS_ORG
    open-dora:
      # Point this at your OpenDORA backend URL
      apiBaseUrl: https://opendora-opendora.apps.sno.neat-monster.com/
    extensions:
      installation:
        enabled: true
        saveToSingleFile:
          file: /tmp/installed-extensions.json
    events:
      http:
        enabled: true
        basePath: /events
    techdocs:
      builder: 'local'
      publisher:
        type: 'local'
    search:
      collators:
        techdocs:
          enabled: true
          schedule:
            frequency: { minutes: 30 }
            initialDelay: { seconds: 20 }
            timeout: { minutes: 5 }       
